services:
  # Backend Web Service
  - type: web
    name: traceroute-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build:server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://your-frontend-url.onrender.com
    
  # Frontend Static Site
  - type: web
    name: traceroute-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SERVER_URL
        value: https://traceroute-backend.onrender.com
